# Generated by Django 2.0.3 on 2018-04-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='message', max_length=1500)),
                ('is_sender_patient', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('appointment_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='health_attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='key', max_length=50)),
                ('value', models.CharField(default='value', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='health_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='default', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('health_attr', models.ManyToManyField(to='home.health_attr')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_release', models.IntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=75)),
                ('doctors', models.ManyToManyField(to='home.doctor')),
                ('insurance', models.ManyToManyField(to='home.insurance')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='health_instance',
            name='insurances',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.insurance'),
        ),
        migrations.AddField(
            model_name='health_instance',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
        migrations.AddField(
            model_name='doctor_appointment',
            name='health_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.health_instance'),
        ),
        migrations.AddField(
            model_name='doctor_appointment',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
        migrations.AddField(
            model_name='communication',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AddField(
            model_name='communication',
            name='health_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.health_instance'),
        ),
        migrations.AddField(
            model_name='communication',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
    ]
