# Generated by Django 2.0.3 on 2018-04-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_instance',
            old_name='insurances',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='insurance',
            new_name='insurances',
        ),
    ]
