# Generated by Django 2.0.3 on 2018-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180407_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(default='general', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
