# Generated by Django 2.0.3 on 2018-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180407_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_instance',
            name='description',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
