# Generated by Django 2.0.3 on 2018-04-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_prescription_health_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
