# Generated by Django 2.0.3 on 2018-04-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_prescription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='is_sender_patient',
        ),
    ]
