# Generated by Django 2.0.3 on 2018-04-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_communication_is_sender_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_appointment',
            name='appointment_time',
            field=models.DateTimeField(default='12/12/2020 14:00'),
        ),
    ]
